NASA-LIS/LISF

lvt/core/LVT_historyMod.F90, lvt/core/LVT_readMetricsAttributes.F90, lvt/core/LVT_statsDataMod.F90, lvt/core/LVT_statsMod.F90, lvt/metrics/LVT_KmeansMod.F90, lvt/plugins/LVT_metric_pluginMod.F90, lvt/plugins/LVT_pluginIndices.F90
Adds the support for K-means clustering as a new metric in LVT
Works on a time series data and creates maps of clusters for the
mean and standard deviation of the time series
implements feature/18
=> enable kmeans clustering support in LVT

docs/howto_create_lis_testcases/howto_create_lis_testcases.adoc
This adds an important admonition to not commit tar files into the repository.
=> Update How to create LIS test cases document

ldt/DAobs/NASA_SMAPsm/readNASASMAPsmObs.F90, lis/dataassim/obs/NASA_SMAPsm/read_NASASMAPsm.F90, lvt/datastreams/SMAPsm/readSMAPsmobs.F90
=> Initialize offset_file variable

lis/testcases/surfacemodels/land/noahmp.3.6_cmem3/input.ctl, lis/testcases/surfacemodels/land/noahmp.3.6_cmem3/output.ctl, lis/testcases/surfacemodels/land/noahmp.3.6_cmem3/testcase.ctl
=> Correct dimensions of running domain

lis/testcases/surfacemodels/land/noahmp.3.6_cmem3/output.ctl, lis/testcases/surfacemodels/land/noahmp.3.6_cmem3/testcase.ctl
=> Correct TDEF for NoahMP3.6_CMEM3 testcase GrADS descriptor files

lis/core/LIS_fileIOMod.F90
number 111. Modified core/LIS_fileIOMode.F90, routine LIS_create_output_directory
Resolves: #34
=> Bug fix for github issue number 34, the same as old trac system's ticket 111

ldt/core/LDT_domainMod.F90, lis/core/LIS_domainMod.F90, lvt/core/LVT_domainMod.F90
=> Correct issue with aspect parameter field index

lis/dataassim/obs/NASA_SMAPvod/NASASMAPvod_Mod.F90, lis/dataassim/obs/NASA_SMAPvod/read_NASASMAPvod.F90, lis/dataassim/obs/NASA_SMAPvod/write_NASASMAPvodobs.F90, lis/make/default.cfg, lis/plugins/LIS_DAobs_pluginMod.F90, lis/plugins/LIS_lsmda_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90
This update enables the capability to assimilate vegetation
optical depth retrievals from SMAP within LIS. The data is
rescaled into the LAI space before assimilating
Resolves #91
=> Adds the capability for SMAP VOD assimilation

lvt/datastreams/ISMN/readISMNObs.F90, lvt/interp/compute_vinterp_weights.F90
The vertical interpolation code has been updated to provide
positive weights. Additional checks have been included in the ISMN
reader to scan for zero/negative weights
Resolves #95
=> Updates the diagnostic checks in the LVT ISMN reader

lis/make/default.cfg, lis/plugins/LIS_lsmrtm_pluginMod.F90, lis/surfacemodels/land/noah.3.6/sfc_cmem3/noah36_sfc2cmem3.F90, lis/testcases/surfacemodels/land/noah.3.6_cmem3/MODEL_OUTPUT_LIST.TBL, lis/testcases/surfacemodels/land/noah.3.6_cmem3/README, lis/testcases/surfacemodels/land/noah.3.6_cmem3/input.ctl, lis/testcases/surfacemodels/land/noah.3.6_cmem3/ldt.config, lis/testcases/surfacemodels/land/noah.3.6_cmem3/lis.config, lis/testcases/surfacemodels/land/noah.3.6_cmem3/output.ctl, lis/testcases/surfacemodels/land/noah.3.6_cmem3/testcase.ctl
Testcase tar files are found here:
/discover/nobackup/pshellit/lisFromGitHub/projectWork/noah36cmem3_tarfiles/
Resolves #53
=> Feature/noah 3.6 cmem3 plugin

lis/dataassim/perturb/gmaopert/landpert_routines.F90
Domin id was added to the initializing the perturbation seed. This will solve the checkerboard and stripe patterns in the DA results.
=> Fixing the DA perturbation issue

ldt/core/LDT_climateParmsMod.F90, ldt/core/LDT_paramProcMod.F90, ldt/params/climateparms/read_NLDAS_climppt.F90, ldt/params/climateparms/read_PRISM_climppt.F90, ldt/params/climateparms/read_WorldClim_climppt.F90
=> Initialize tmin and tmax sources

lis/metforcing/gdas/read_gdas.F90
This code adds a check to the reader to prevent the user from using either
3hr - 6hr LIS model timesteps or prevents the user from using a 6hr model
timestep with a 6hr or greater model output interval. These options will cause the incorrect
data to be written in the LIS output files.
This is not a bug fix. This just temporarily prevents the user from generating
inaccurate output files until a true bug fix is implemented.
(Associated with issue #67 )
=> LIS GDAS reader 3hr bug warning

lvt/datastreams/IMERG/readIMERGdata.F90
=> Fixed syntax errors in LVT IMERG reader (issue #139)

ldt/LDTSI/LDTSI_gofsMod.F90
=> Fix for issue #148

lvt/arch/Config.pl
Overall logic and flags borrowed from LIS Config.pl.
Fixes issue #136.
=> Added strict check settings for GNU compilers.

docs/working_with_github/working_with_github.adoc
=> Update "Collaborating with others" section in the "Working with GitHub" document

ldt/DAobs/NASA_SMAPvod/NASASMAPvod_obsMod.F90, ldt/DAobs/NASA_SMAPvod/readNASASMAPvodObs.F90
This commit adds the support for processing the VOD retrievals from the SMAP L2 data. The earlier version of the code relied on the L3 data, which only contain the climatological VOD
Resolves #170
=> Adds the support for SMAP L2 VOD retrievals

lis/make/default.cfg, lis/plugins/LIS_lsmda_pluginMod.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_daldtsi_Mod.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_descale_ldtsi.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_getldtsipred.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_getldtsivars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_ldtsi_update.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_map_ldtsi.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_qc_ldtsiobs.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_qcldtsi.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_scale_ldtsi.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_setldtsivars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_transform_ldtsi.F90, lis/surfacemodels/land/noahmp.4.0.1/da_ldtsi/noahmp401_updateldtsivars.F90
Cleaned up and resubmitted pull request.
See old pull request #144.
=> Feature/noahmp401 ldtsi da for 557WW

lvt/configs/lvt.config.master, lvt/core/LVT_optUEMod.F90
The LVT OPT/UE reader has been updated to work with the format of
output from LIS
Resolves #179
=> Fixes the bug of LVT not reading the OPT/UE outputs correctly

lvt/utils/afwa/convert_nc2surf.py
Soil moisture is adjusted to be no less than 0.1 times the wilting point.
Also, negative snow depth is reset to zero.
=> Updates to improve initialization of GALWEM.

lvt/datastreams/APHRO_PRCP/readAPHROPRCPObs.F90
Support APHRODITE-2  V1101EX_R1 (2007-2015), Monsoon Asia
=> Update file name for APHRODITE product for 2007-2015

lvt/core/LVT_LISoutputHandlerMod.F90
The bug fix allows the calculation of ensemble mean values from the LIS
ensemble
Fixes #363
=> Allows ensemble averaging of LIS ensemble outputs

lis/core/LIS_historyMod.F90, lis/testcases/surfacemodels/land/noah.3.6_restart/MODEL_OUTPUT_LIST.TBL, lis/testcases/surfacemodels/land/noah.3.6_restart/README, lis/testcases/surfacemodels/land/noah.3.6_restart/input.ctl, lis/testcases/surfacemodels/land/noah.3.6_restart/input.xdf, lis/testcases/surfacemodels/land/noah.3.6_restart/input_testcase.ctl, lis/testcases/surfacemodels/land/noah.3.6_restart/ldt.config, lis/testcases/surfacemodels/land/noah.3.6_restart/lis.config, lis/testcases/surfacemodels/land/noah.3.6_restart/output.ctl, lis/testcases/surfacemodels/land/noah.3.6_restart/testcase.ctl
This fixes the insufficient memory error that Yonghwan was getting when running NoahMP 4.0.1.
=> Fix read restart

lvt/utils/afwa/templates/MODEL_OUTPUT_LIST.TBL.lvt_557post.RelSMC_inst.3hr, lvt/utils/afwa/templates/make_lvt_config_24hr_noahmp.py, lvt/utils/afwa/templates/make_lvt_config_3hr_jules.py, lvt/utils/afwa/templates/make_lvt_config_3hr_noah.py, lvt/utils/afwa/templates/make_lvt_config_3hr_noahmp.py, lvt/utils/afwa/templates/submit_lvt_conrad_24hr_noahmp.py, lvt/utils/afwa/templates/submit_lvt_conrad_3hr_jules.py, lvt/utils/afwa/templates/submit_lvt_conrad_3hr_noahmp.py, lvt/utils/afwa/templates/submit_lvt_discover_24hr_noahmp.py, lvt/utils/afwa/templates/submit_lvt_discover_3hr_jules.py, lvt/utils/afwa/templates/submit_lvt_discover_3hr_noahmp.py
* Added Python scripts for postprocessing NoahMP.4.0.1.
* Added Albedo_tavg and SmLIqFrac_inst for JULES.
* Removed Greenness_inst for JULES (this variable comes from LDT, and is not used by JULES)
* Fixed units for RelSMC to be consistent with 557WW GRIB2 table.
=> LVT updates for LISF 7.3 Ops

lis/core/LIS_create_subdirs.c
Changed LIS_create_subdirs to check if path exists before calling mkdir.
=> Revised LIS_create_subdirs to check if path exists before calling mkdir.

lis/core/LIS_create_subdirs.c, lis/core/LIS_forecastMod.F90, lis/core/LIS_readConfig.F90
(1) Make sure only master process creates directory
(2) Simplify check of stat function call
=> More fixes to creating output directories

lvt/core/LVT_LISoutputHandlerMod.F90, lvt/core/LVT_histDataMod.F90
Added "-" units for RelSMC in LVT.
This is an operational requirement for AFW.
=> CRITICAL BUG FIX:  Added "-" units for RelSMC in LVT

ldt/LDTSI/LDTSI_analysisMod.F90, ldt/LDTSI/ldt.config.sample, lvt/configs/lvt.config.ldtsi
(1) Added sanity checks to iceage to ensure valid value exists when icemask is valid.   See commit 4033181 for more info.
(2) Cleaned up ldt.config.sample for running LDTSI
(3) Added sample lvt.config file for processing LDTSI output.
=> Bug fixes for LDTSI

ldt/DAobs/NASA_SMAPsm/readNASASMAPsmObs.F90, lis/dataassim/obs/NASA_SMAPsm/NASASMAPsm_Mod.F90, lis/dataassim/obs/NASA_SMAPsm/read_NASASMAPsm.F90, lvt/datastreams/SMAP_L3TB/SMAP_L3TBMod.F90, lvt/datastreams/SMAP_L3TB/readSMAP_L3TB.F90, lvt/datastreams/SMAPsm/SMAP_smobsMod.F90, lvt/datastreams/SMAPsm/readSMAPsmobs.F90, lvt/datastreams/SMAPvwc/SMAP_vwcobsMod.F90, lvt/datastreams/SMAPvwc/readSMAPvwcobs.F90
We had to redo this pull request.  Please see #196 for the full history of this pull request.
Test case for LVT SMAP reader is available at
/discover/nobackup/mnavari/my_projects/op/test_new_smap_reader4lvt
Test case for soil moisture DA using new reader is available at /discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader
Test case for LDT:
/discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader_ldt
=> The SMAP reader was modified to read the SMAP L3 file with the latest Release number and largest CRID Version Number

lis/make/default.cfg, lis/plugins/LIS_lsmda_pluginMod.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_dasnodep_Mod.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_descale_snodep.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_getsnodeppred.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_getsnodepvars.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_map_snodep.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_qc_snodepobs.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_qcsnodep.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_scale_snodep.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_setsnodepvars.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_snodep_update.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_transform_snodep.F90, lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_updatesnodep.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_dausafsi_Mod.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_descale_usafsi.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_getusafsipred.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_getusafsivars.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_map_usafsi.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_qc_usafsiobs.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_qcusafsi.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_scale_usafsi.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_setusafsivars.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_transform_usafsi.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_updateusafsi.F90, lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_usafsi_update.F90
Snow DA interface (SNODEP & USAFSI) for LIS-JULES5x container. 
Test case (CONUS):
/discover/nobackup/yyoon4/JULES5X/SRC/jules.5.x
lis.config.snodep -> SNODEP DA
lis.config.usafsi    -> USAFSI DA
=> Snow DA interface for LIS-JULES5X container

lis/plugins/LIS_lsmda_pluginMod.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_dasoilm_Mod.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_descale_soilm.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_getLbandTbPred.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_getsmpred.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_getsoilm.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_qc_soilmobs.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_qcsoilm.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_scale_soilm.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_setsoilm.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_updatesoilm.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_write_soilm.F90
(1) soil moisture DA code has been updated for JULES 5.x
(2) LIS plugin files have been updated for supporting JULES 5.x soil moisture DA 
A test case is in /discover/nobackup/swang9/For/Yonghwan/DA_5x/ .
=> Soil moisture DA for JULES 5.x

ldt/arch/Config.pl, lis/arch/Config.pl, lis/make/Makefile, lvt/arch/Config.pl
Cherry-pick updates to the Config.pl files to allow support/lisf-557ww-7.3 branch to compile on discover on the SLES 12.3 nodes.
=> Support for compiling on SLES 12

lis/dataassim/algorithm/pf/pf_Mod.F90, lis/dataassim/algorithm/pf/pf_general.F90, lis/dataassim/algorithm/pf/pf_types.F90, lis/dataassim/obs/syntheticsnd/read_syntheticsndobs.F90, lis/make/default.cfg, lis/plugins/LIS_lsmda_pluginMod.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_dasnow_Mod.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_descale_snow.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_getsnowpred.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_getsnowvars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_qc_snowobs.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_qcsnow.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_scale_snow.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_setsnowvars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_snow_update.F90, lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_updatesnowvars.F90
Particle Filter algorithm as another data assimilation algorithm has been added
PF is a monte carlo algorithm where assumptions of gaussianty is not required.
Resolves #507
=> Adds the implementation of particle filter assimilation algorithm

lis/make/default.cfg, lis/optUE/type/paramestim/obs/UAsnow/UAsnow_obsMod.F90, lis/optUE/type/paramestim/obs/UAsnow/read_UAsnowobs.F90, lis/optUE/type/paramestim/obs/UAsnow/reset_UAsnowobs.F90, lis/optUE/type/paramestim/obs/UAsnow/write_UAsnowobs.F90, lis/plugins/LIS_PEobs_pluginMod.F90, lis/plugins/LIS_lsmoptue_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90, lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90, lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_module.F90, lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_read_OPT_parameters.F90, lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_setup.F90, lis/surfacemodels/land/noahmp.4.0.1/noahmp_driver_401.F90, lis/surfacemodels/land/noahmp.4.0.1/pe/NoahMP401_peMod.F90, lis/surfacemodels/land/noahmp.4.0.1/pe/NoahMP401_set_pedecvars.F90, lis/surfacemodels/land/noahmp.4.0.1/pe/obspred/UAsnow/NoahMP401_getpeobspred_UAsnowobs.F90, lis/surfacemodels/land/noahmp.4.0.1/pe/obspred/UAsnow/NoahMP401_setupobspred_UAsnowobs.F90, lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90
This updates includes the following changes:
1. NoahMP401 has been updated to enable spatially distributed specification of model parameters
2. This also allows the parameters to be exposed for optimization
3. Added interfaces for parameter estimation within Noahmp401
4. Added support for University of Arizona snow data for use in parameter estimation
Resolves #514
=> Enables calibration interfaces in NoahMP401

lvt/configs/METRICS.TBL, lvt/configs/METRICS.TBL.adoc, lvt/core/LVT_readMetricsAttributes.F90, lvt/core/LVT_statsDataMod.F90, lvt/core/LVT_statsMod.F90, lvt/metrics/LVT_JointEntropyMod.F90, lvt/plugins/LVT_metric_pluginMod.F90, lvt/plugins/LVT_pluginIndices.F90
This commmit adds the support for the joint entropy metric
calculation
Related to #524
=> Implements the joint entropy method

lvt/configs/METRICS.TBL, lvt/configs/METRICS.TBL.adoc, lvt/core/LVT_readMetricsAttributes.F90, lvt/core/LVT_statsDataMod.F90, lvt/core/LVT_statsMod.F90, lvt/metrics/LVT_RelativeEntropy.F90, lvt/plugins/LVT_metric_pluginMod.F90, lvt/plugins/LVT_pluginIndices.F90
This commit includes the implementation for the Relative Entropy or
Kullback-Leibler divergence metric. This metric is a measure of
how one probability distribution is different from another probability
distribution
Relative Entropy values are calculated as:
H(X)= Sum_x  P(x)log [P(x)/Q(x)]
related to #525
=> Implements the relative entropy metric in LVT

lvt/core/LVT_LISoutputHandlerMod.F90, lvt/core/LVT_LMLCMod.F90, lvt/core/LVT_PRIV_rcMod.F90, lvt/core/LVT_coreMod.F90, lvt/core/LVT_domainMod.F90, lvt/core/LVT_readConfig.F90, lvt/core/LVT_soilsMod.F90, lvt/core/LVT_topoMod.F90, lvt/metrics/LVT_InformationEntropyMod.F90, lvt/metrics/LVT_MaxTimeMod.F90, lvt/metrics/LVT_MinTimeMod.F90
The time lag specification has been extended for all three
datastreams
Resolves #541
=> Updated LVT to have more flexible time lag computations

lis/dataassim/obs/NASA_SMAPsm/NASASMAPsm_Mod.F90, lis/dataassim/obs/NASA_SMAPsm/read_NASASMAPsm.F90
I cherry-picked LIS NASA_SMAPsm commits on the master branch into the support/lisf-557ww-7.3 branch.  These commits contain updates to the quality checking of the SPL3SMP datasets, and they are needed for analysis and spin-up runs for the USAF project.
=> Back merge NASA_SMAPsm reader updates

lis/dataassim/obs/NASA_SMAPvod/NASASMAPvod_Mod.F90, lis/dataassim/obs/NASA_SMAPvod/read_NASASMAPvod.F90
I cherry-picked LIS NASA_SMAPvod commits on the master branch into the support/lisf-557ww-7.3 branch. These commits contain updates to add support for assimilating NASA SMAP VOD retrievals in LIS.
=> Back merge NASA_SMAPvod reader updates

lvt/core/LVT_LISoutputHandlerMod.F90, lvt/core/LVT_histDataMod.F90
Included vapor pressure deficit among the supported
variables
Resolves #560
=> Added the support for processing VPD

docs/LVT_users_guide/LVT_usersguide.adoc, docs/LVT_users_guide/revision_table.adoc, lvt/configs/lvt.config.adoc
I made sure that the "Building the Executable" section and the "LVT config File" section were up to date.
=> Update LVT Users' Guide for 557WW 7.3.0 release

docs/LIS_users_guide/LIS_usersguide.adoc, docs/LIS_users_guide/revision_table.adoc
I made sure that the "Building the Executable" section and the "LIS config File" section were up to date.
=> Update LIS Users' Guide for 557WW 7.3.0 release

docs/LDT_users_guide/LDT_usersguide.adoc, docs/LDT_users_guide/revision_table.adoc
I made sure that the "Building the Executable" section and the "LDT Config File" section were up to date.
=> Update LDT Users' Guide for 557WW 7.3.0 release

lis/configs/557WW-7.3-FOC/ldt.config.global.jules50.cdf, lis/configs/557WW-7.3-FOC/ldt.config.global.jules50.ensemble, lis/configs/557WW-7.3-FOC/ldt.config.global.noah39.cdf, lis/configs/557WW-7.3-FOC/ldt.config.global.noah39.ensemble, lis/configs/557WW-7.3-FOC/ldt.config.global.noahmp401.cdf, lis/configs/557WW-7.3-FOC/ldt.config.global.noahmp401.ensemble
Adding sample ldt.config files for soil moisture CDF generation
and for ensemble restart file generation for all three LSMs for
the 557WW-7.3-FOC environment.
=> Add sample CDF and ensemble restart ldt.config files for 557WW

lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
The duplicate piece of code that was introduced erroneously has now been removed
Resolves #588
=> Removes the bug in the albedo calculations

lvt/utils/afwa/templates/submit_lvt_koehr_24hr_jules.py, lvt/utils/afwa/templates/submit_lvt_koehr_24hr_noah.py, lvt/utils/afwa/templates/submit_lvt_koehr_24hr_noahmp.py, lvt/utils/afwa/templates/submit_lvt_koehr_3hr_jules.py, lvt/utils/afwa/templates/submit_lvt_koehr_3hr_noah.py, lvt/utils/afwa/templates/submit_lvt_koehr_3hr_noahmp.py
Sorry Eric.  I misspelled the name of the modulefile used on koehr.
=> Correct the name of the modulefile used on koehr

docs/LIS_users_guide/build.adoc
Document libraries used on conrad and gaffney.
=> Update build section in LIS Users' Guide

ldt/USAFSI/USAFSI_netcdfMod.F90
Fix just one minor typo in the USAF-SI reader. For this change, I do not create a test case. However, if you need the test case for verification purposes, please let me know.
=> [LDT: USAF-SI] Fix typo

lvt/configs/lvt.config.usafsi, lvt/core/LVT_PRIV_rcMod.F90, lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90, lvt/runmodes/USAFSIpost/LVT_init_USAFSIpost.F90, lvt/runmodes/USAFSIpost/LVT_run_USAFSIpost.F90, lvt/runmodes/USAFSIpost/lvt.config.example
Added two new GRIB1 file options based on last-minute communication of customer requirements.  Also improved
toggling on/off of different GRIB output files.
This will need to be merged into master as well.
=> Added two new "SNODEP" GRIB1 output files.  Updated GRIB output logic.

ldt/testcases/DAobs_SMAP/README, ldt/testcases/DAobs_SMAP/ldt.config, lis/testcases/dataassim/nasa_smap_enkf_noah36/MODEL_OUTPUT_LIST.TBL, lis/testcases/dataassim/nasa_smap_enkf_noah36/README, lis/testcases/dataassim/nasa_smap_enkf_noah36/lis.config, lis/testcases/dataassim/nasa_smap_enkf_noah36/output.ctl, lis/testcases/dataassim/nasa_smap_enkf_noah36/testcase.ctl, lvt/testcases/datastreams/nasa_smap/README, lvt/testcases/datastreams/nasa_smap/lvt.config
=> Add testcase for SMAP soil moisture da

ldt/USAFSI/USAFSI_analysisMod.F90
Fixes a bug where Bratseth could insert snow depth where the satellite-derived snow cover was zero.
=> Reconciled Bratseth snow depth to snow cover field.

ldt/configs/ldt.config.adoc, ldt/configs/ldt.config_master
Merge updates made to the old LaTeX version of the LDT runtime configuration documentation into the new AsciiDoc version.
=> Merge updates into ldt.config.adoc file

docs/LIS_users_guide/LIS_usersguide.adoc, docs/LIS_users_guide/obtain-source.adoc
I will ask the lab to help fill in the "specifies what?" blanks after I finish the rest of the updates to this document.
=> Update section "Obtaining the Source Code" in LIS Users' Guide for LISF 7.3 release

ldt/configs/ldt.config.adoc, lis/configs/lis.config.adoc
Thanks David/dmocko and Kristi/karsenau.
=> Correct broken links in Users' Guides for LISF 7.3 release

lis/configs/lis.config.adoc, lis/dataassim/obs/MCD15A2H_LAI/MCD15A2Hlai_Mod.F90, lis/dataassim/obs/MCD15A2H_LAI/read_MCD15A2Hlai.F90, lis/dataassim/obs/MCD15A2H_LAI/write_MCD15A2Hlai.F90, lis/make/default.cfg, lis/plugins/LIS_DAobs_pluginMod.F90, lis/plugins/LIS_lsmda_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_daveg_Mod.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_descale_veg.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_getLAIpred.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_getvegvars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_qc_LAIobs.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_qcveg.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_scale_veg.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_setvegvars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_updatevegvars.F90, lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_write_veg.F90
add features supporting assimilating MCD15A2H LAI product into Noah-MP.4.0.1, including:
1. lai_da for Noah-MP.4.0.1 contributed by Sujay
2. a reader for the MODIS MCD15A2H LAI product
=> lai_da for noahmp.4.0.1 and MODIS MCD15A2H LAI reader for LIS

lis/testcases/surfacemodels/land/geowrsi.2/MODEL_OUTPUT_LIST.TBL, lis/testcases/surfacemodels/land/geowrsi.2/README, lis/testcases/surfacemodels/land/geowrsi.2/input.ctl, lis/testcases/surfacemodels/land/geowrsi.2/input.xdf, lis/testcases/surfacemodels/land/geowrsi.2/input_testcase.ctl, lis/testcases/surfacemodels/land/geowrsi.2/ldt.config, lis/testcases/surfacemodels/land/geowrsi.2/lis.config_sos, lis/testcases/surfacemodels/land/geowrsi.2/lis.config_wrsi, lis/testcases/surfacemodels/land/geowrsi.2/output_sos.ctl, lis/testcases/surfacemodels/land/geowrsi.2/output_sosa.ctl, lis/testcases/surfacemodels/land/geowrsi.2/output_wrsi.ctl, lis/testcases/surfacemodels/land/geowrsi.2/testcase_sos.ctl, lis/testcases/surfacemodels/land/geowrsi.2/testcase_sosa.ctl, lis/testcases/surfacemodels/land/geowrsi.2/testcase_wrsi.ctl, lis/testcases/surfacemodels/land/geowrsi.2/wget_testcasefiles_portal.sh
This was inadvertently removed when I cleaned up the obsolete public
testcases.
=> Reinstate the geowrsi2 testcase

lis/configs/lis.config.adoc
Removed `devonly` block and fixed formatting.
=> Fix formatting of MODIS LAI options.

lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.jules50.discover, lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.noah39.discover, lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.noahmp401.discover, lis/configs/557WW-7.3-FOC/lis.config.global.jules50.ops, lis/configs/557WW-7.3-FOC/lis.config.global.jules50.ops.galwem10, lis/configs/557WW-7.3-FOC/lis.config.global.jules50.retrospective, lis/configs/557WW-7.3-FOC/lis.config.global.noah39.ops, lis/configs/557WW-7.3-FOC/lis.config.global.noah39.ops.galwem10, lis/configs/557WW-7.3-FOC/lis.config.global.noah39.retrospective, lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.ops, lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.ops.galwem10, lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.retrospective
This pull request updates the example 557WW-7.3-FOC lis.config
files to the current retrospective and ops (operational) 557WW
configurations.
=> Update 557WW-7.3-FOC lis.config examples to current settings

lis/configs/lis.config.adoc, lis/metforcing/gefs/gefs_forcingMod.F90, lis/metforcing/gefs/get_gefs.F90, lis/metforcing/gefs/read_gefs_operational.F90, lis/metforcing/gefs/readcrd_gefs.F90, lis/metforcing/gefs/timeinterp_gefs.F90
Updates the GEFS forcing plugin to support the new operational data streams
Resolves #698
=> Updates the GEFS forcing plugin

lis/core/LIS_readConfig.F90
The default option has been changed to 'off'
Resolves #703
=> Turned off the stats file output

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/pull_request_template.md
Add Issue and Pull Request templates to the LISF GitHub experience. More info on this feature [here](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates). 
Test drive these templates:
* [Issues](https://github.com/bmcandr/lisf-test/issues/new/choose)
* [Pull request](https://github.com/bmcandr/lisf-test/compare/master...bmcandr:feature/test-pr-template)
Resolves #701
=> Add GitHub Issue and Pull Request templates

ldt/configs/ldt.config.adoc
Updated LDT documentation to reflect all available running modes in plugins/LDT_pluginIndices.F90
Resolves #712
=> Update LDT documentation to reflect all run modes

docs/LDT_users_guide/LDT_usersguide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LIS_users_guide/LIS_usersguide.adoc, docs/LIS_users_guide/revision_table.adoc, docs/LVT_users_guide/LVT_usersguide.adoc, docs/LVT_users_guide/revision_table.adoc
I updated revision history for the Users' Guides for the LISF Public 7.3.1 release.
Resolves #751
=> Update revision history for the Users' Guides for the LISF Public 7.3.1 release

lis/dataassim/obs/GCOMW_AMSR2L3SND/GCOMW_AMSR2L3SND_Mod.F90, lis/dataassim/obs/GCOMW_AMSR2L3SND/read_GCOMW_AMSR2L3SND.F90, lis/dataassim/obs/MODISsca/read_MODISscaobs.F90, lis/plugins/LIS_lsmda_pluginMod.F90
LIS DA plugin updated to support AMSR2 snow depth DA and NoahMP401. GCOMW_AMSR2L3SND reader also updated to fix a unit mismatch between NoahMP401 and AMRS2. Use of MOD10C1 collection 5 has been replaced with collection 6 to support DA through the present.
Resolves #758 
Testcase available within EIS Freshwater project space
/discover/nobackup/project/eis_freshwater/mwrzesie/DA_AMSR2_snowdepth
=> Add AMSR2 snow depth DA to NoahMP.4.0.1

ldt/configs/ldt.config.adoc, lis/configs/lis.config.adoc, lvt/configs/lvt.config.adoc
Add documentation for THySM config options to LDT, LIS, and LVT user guides. Follow up to #756.
Targets *eis-freshwater* branch.
=> Add documentation for THySM config options

lis/testcases/dataassim/smos_nrt_nn_l2sm/MODEL_OUTPUT_LIST.TBL, lis/testcases/dataassim/smos_nrt_nn_l2sm/README, lis/testcases/dataassim/smos_nrt_nn_l2sm/input.ctl, lis/testcases/dataassim/smos_nrt_nn_l2sm/input_testcase.ctl, lis/testcases/dataassim/smos_nrt_nn_l2sm/ldt.config, lis/testcases/dataassim/smos_nrt_nn_l2sm/ldt.config.da, lis/testcases/dataassim/smos_nrt_nn_l2sm/lis.config, lis/testcases/dataassim/smos_nrt_nn_l2sm/output.ctl, lis/testcases/dataassim/smos_nrt_nn_l2sm/testcase.ctl
This adds the smos_nrt_nn_l2sm reader testcase configuration files.
Resolves #745
=> Add smos_nrt_nn_l2sm testcase configuration files

lis/surfacemodels/land/jules.5.0/couple_jules_to_lis.sh
The script (lis/surfacemodels/land/jules.5.0/couple_jules_to_lis.sh) has been updated to add David's code change (./src/science/soil/soil_htc_jls_mod.F90) for preventing LIS-JULES crash.
Shugong Wang
=> couple_jules_to_lis.sh modification 

ldt/core/LDT_forcingparms_Ftable.c, ldt/core/LDT_irrig_Ftable.c, ldt/make/makedep.py, lis/make/makedep.py, lis/make/user_557ww.cfg, lis/surfacemodels/land/jules.5.0/da_soilm/jules50_getsmpred.F90, lis/surfacemodels/land/jules.5.0/da_soilm/jules50_getsoilm.F90, lis/surfacemodels/land/jules.5.0/da_soilm/jules50_qc_soilmobs.F90, lis/surfacemodels/land/jules.5.0/da_soilm/jules50_setsoilm.F90, lis/surfacemodels/land/jules.5.2/da_soilm/jules52_getsmpred.F90, lis/surfacemodels/land/jules.5.2/da_soilm/jules52_qc_soilmobs.F90, lis/surfacemodels/land/jules.5.3/da_soilm/jules53_getsmpred.F90, lis/surfacemodels/land/jules.5.3/da_soilm/jules53_qc_soilmobs.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_getsmpred.F90, lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_qc_soilmobs.F90, lvt/make/makedep.py, lvt/utils/gnuplot/timeseries/plotTS.py
Address SonarQube findings for LISF 557WW 7.4.0.  See Issue #763 for a list of the findings.
Resolves #763
=> Address SonarQube findings for LISF 557WW 7.4.0

lis/dataassim/obs/GLASS_LAI/read_GLASSlai.F90, lis/dataassim/obs/MCD15A2H_LAI/read_MCD15A2Hlai.F90
=> add fix to the MCD15A2H and GLASS LAI-DA readers

lis/configs/557WW-7.4-FOC/attribs/usafsi_attribs.txt, lis/configs/557WW-7.4-FOC/attribs/usafsi_pertattribs.txt
Changing the USAFSI attribs and pertattribs files.
The text previously said SNODEP obs, but changing to USAFSI obs.
This change does not affect the simulation, but correcting for completeness and for accurate reporting in the log files.
=> Update USAFSI attribs files

ldt/DAobs/ESACCI_sm/readESACCIsmObs.F90, lis/dataassim/obs/ESACCI_sm/read_ESACCIsm.F90
Add support to LDT & LIS ESA-CCI readers to read combined product versions >2.2. Users can now use any version after 2.2. Additional supports for (possible) future ESA-CCI version > 10.0 are also included (if the product still uses this format for the future version, otherwise the code can be edited).
The same LDT and LIS configs can be used, e.g.,
LDT
----
ESA CCI soil moisture observation directory: ./CCI_SM_v03.2/data/combined
ESA CCI soil moisture version of data:       3.2
LIS
----
ESA CCI soil moisture data directory:      ./CCI_SM_v03.2/data/combined
ESA CCI soil moisture data version:        3.2
=> Update ESA-CCI readers (LDT & LIS) to read combined product versions >2.2

lvt/utils/afwa/make_sm_geotiff.py
Updated make_sm_geotiff.py to add metadata to GeoTIFF files.  Also changed soil layer numbering from 0-3 to 1-4.
=> Added metadata to GeoTIFF files. Also changed layer numbering.

docs/README.adoc
Updates the documentation README.
Change summary:
* Remove references to LaTeX+TeX since we have switched to AsciiDoc
* Update Web Browser section
* Add instructions for viewing documentation directly from GitHub 
* Add links directly to "raw" files; these will render with AsciiDoc.js Live Preview installed
* Change references to LIS to LISF where appropriate
View the rendered version of these changes here: https://github.com/NASA-LIS/LISF/blob/d270ae09563970ade68912def407ac4b0950ac05/docs/README.adoc
=> Update documentation README

ldt/configs/ldt.config.adoc
Late breaking change requested in `ldt.config.adoc` related to #867. Updates mask data resolution from 25km to 1km.
=> Fix OSSE mask resolution examples

lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90, lis/surfacemodels/land/noahmp.4.0.1/noahmp_driver_401.F90, lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90, lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
=> Add PET code from Sujay to Noah-MP

lvt/datastreams/MCD15A2H/readMCD15A2Hobs.F90
Clean up as part of EIS Freshwater branch review.
Related to PR #773.
=> Updates to MCD15A2H LAI reader

ldt/configs/ldt.config.adoc, ldt/core/LDT_irrigationMod.F90, ldt/params/irrigation/read_USGSNative_irriggwratio.F90, ldt/params/irrigation/setIrrigParmsFullnames.F90, ldt/params/irrigation/set_irriggwratio_attribs.F90, lis/irrigation/sprinkler/sprinkler_irrigationMod.F90, lis/runmodes/smootherDA/smootherDA_runMod.F90, lis/surfacemodels/land/noahmp.4.0.1/irrigation/noahmp401_getirrigationstates.F90
Cleanup as part of EIS FW branch review. Changes include:
* Minor edits to log messages
* Fix for `noahmp401_getirrigationstates.F90` suggested by @dmocko in #777 discussion
* Fixes approved by @KathyNie in #777 discussion
Compiles without issue.
=> Cleanup PR 777

lis/configs/lis.config.adoc
Adds config entries for SNODAS DA to the LIS documentation.  Related to #764:
https://github.com/mlwrzesien/LISF/blob/be68ee58798f949efe268b7763fe5e6079d2cfc8/lis/dataassim/obs/SNODAS/SNODAS_Mod.F90#L131-L132
=> Add SNODAS DA config documentation

README.adoc
Updates the top-level README to provide more information/orientation for users that land on our repo. View a rendered version here: https://github.com/bmcandr/LISF/tree/feature/readme-update
=> Update LISF README document

docs/LDT_users_guide/LDT_usersguide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LIS_users_guide/LIS_usersguide.adoc, docs/LIS_users_guide/revision_table.adoc, ldt/configs/ldt.config.adoc
Update documentation for LISF 557WW 7.4.6 release
=> Update documentation for LISF 557WW 7.4.6 release

ldt/utils/usaf/s2s_ensrst/generate_ldtconfig_files_ensrst_nrt.py, lvt/utils/usaf/s2spost/run_s2spost_9months.py
Fix several typos found in S2S Python scripts, intended for use by 557WW.
=> Fix several typos in S2S Python scripts.

docs/README.adoc, docs/discover_quick_start/discover_quick_start.adoc
Adds a Quick Start guide for new LISF users on Discover. This document is a compilation of guidance shared with me by Jim, Eric, David, and others when I joined the LIS team (as well as some things I picked up along the way.)
This document can be viewed on GitHub directly: https://github.com/bmcandr/LISF/blob/feature/discover-quick-start-guide/docs/discover_quick_start/discover_quick_start.adoc
Or as rendered AsciiDoc: https://raw.githubusercontent.com/bmcandr/LISF/feature/discover-quick-start-guide/docs/discover_quick_start/discover_quick_start.adoc
**I welcome any additions or suggested edits!**
=> Add Discover Quick Start Guide

docs/discover_quick_start/discover_quick_start.adoc
Updates modulefile filename in Discover quick start guide
=> Update modulefile filename in Discover quick start guide

lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
This reverts commit d1145fbb41cfd04feeaa228cda243d3647aa46f1.
=> Revert "Temporally turns off the water balance check in NoahMP 4.0.1"

lis/irrigation/sprinkler/sprinkler_irrigationMod.F90
The groundwater irrigation ratio field is an optional field used by the
sprinkler irrigation code when both "Groundwater abstraction for irrigation:"
(LIS_rc%irrigation_GWabstraction) and "Irrigation source water partition:"
(LIS_rc%irrigation_SourcePartition) are enabled in LIS' run-time
configuration file (lis.config).
=> Correct reading of "Groundwater irrigation ratio"

ldt/USAFSI/LDT_usafsiMod.F90, ldt/USAFSI/USAFSI_analysisMod.F90, ldt/USAFSI/USAFSI_galwemMod.F90, ldt/USAFSI/USAFSI_gofsMod.F90, ldt/USAFSI/USAFSI_lisMod.F90, ldt/USAFSI/USAFSI_run.F90, ldt/USAFSI/USAFSI_utilMod.F90, ldt/USAFSI/ldt.config.sample, ldt/configs/ldt.config.adoc, lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90, lvt/utils/usaf/usafsipost/lvt.config.example, lvt/utils/usaf/usafsipost/submit_lvt_usafsipost_discover.py
USAFSI updates for Air Force.
* Added support for FNMOC GRIB1 SST files if GOFS is missing
* Added write statements to better log which files are being searched for, and which are missing
* Minor bug fix to LVT for constructing full path to USAFSI netCDF file.
* Updated sample lvt.config file to fix USAFSI related entry
* Updated LVT scripts to reflect current Discover working environment
No test case.
=> USAFSI updates, including support for SST GRIB1 backup support

docs/LDT_users_guide/LDT_usersguide.adoc, docs/LDT_users_guide/revision_table.adoc
Update the revision history for the upcoming LISF 557WW 7.4.8 release.
=> Update revision history for LISF 557WW 7.4.8 release

lis/configs/lis.config.adoc, lis/core/LIS_LMLCMod.F90, lis/core/LIS_albedoMod.F90, lis/core/LIS_fileIOMod.F90, lis/core/LIS_soilsMod.F90, lis/core/LIS_topoMod.F90, lis/core/LIS_vegDataMod.F90, lis/make/default.cfg, lis/metforcing/gddp/finalize_gddp.F90, lis/metforcing/gddp/gddp_forcingMod.F90, lis/metforcing/gddp/get_gddp.F90, lis/metforcing/gddp/read_gddp.F90, lis/metforcing/gddp/readcrd_gddp.F90, lis/metforcing/gddp/reset_gddp.F90, lis/metforcing/gddp/timeinterp_gddp.F90, lis/plugins/LIS_metforcing_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90
Adds the support for the NEX GDDP climate data as forcing. The plugin
temporally disaggregates the daily GDDP data to subdaily resolution.
The code also updates includes updates to the parameter reading routines
so that in a multiprocessor mode, each process directly reads the subsetted
data slice. The older version of the code read the global data and subsetted it.
Resolves #989
=> Adds the support for the GDDP reader

lis/metforcing/usaf/AGRMET_fldbld_gfs.F90
Fixed data type plevel from real to integer.
=> Fixed data type.

ldt/arch/Config.pl, lis/arch/Config.pl
Add support for compiling on IBM with GNU compilers.
This was tested on ORNL's summit system.
=> Add support for compiling on IBM with GNU compilers

lis/arch/Config.pl
Updated -O2 compiler flags for Cray compiler for LIS.
=> Updated Cray compiler flags for LIS with -O2.

ldt/USAFSI/LDT_usafsiMod.F90, ldt/USAFSI/USAFSI_amsr2Mod.F90, ldt/USAFSI/USAFSI_analysisMod.F90, ldt/USAFSI/USAFSI_run.F90, ldt/USAFSI/USAFSI_ssmisMod.F90, ldt/USAFSI/USAFSI_utilMod.F90, ldt/USAFSI/USAFSI_xcalgmiMod.F90
Extended maximum length of file path variables.  Requested by USAF customer.
=> Extended/standardized file path lengths.

lis/dataassim/obs/ANSA_SNWD/read_ANSASNWDsnow.F90, lis/dataassim/obs/SSMI_SNWD/read_SSMISNWDsnow.F90, lis/metforcing/gdasT1534/get_gdasT1534.F90, lis/metforcing/genEnsFcst/get_genEnsFcst.F90, lis/metforcing/gfs/get_gfs.F90, lis/metforcing/gldas/get_gldas.F90, lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_writerst.F90
I missed a few path length variables in #1014 and fixed them here. Thanks to @karsenau for bringing this to my attention. Sorry I didn't get these in before you merged, @jvgeiger!
=> Expand path length in a few more places

lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90
Changed filename convention for new USAFSI GRIB2 output.
Change requested by SEMS-III contractor and LCMC.
=> Changed filename convention for new USAFSI GRIB2 output.

docs/LIS_users_guide/LIS_usersguide.adoc, docs/LIS_users_guide/revision_table.adoc
Update revision history for the LIS Users' Guide for the LISF Public 7.3.4 release
=> Update revision history for the LIS Users' Guide for the LISF Public 7.3.4 release

docs/LDT_users_guide/LDT_usersguide.adoc, docs/LDT_users_guide/revision_table.adoc
Update revision history for the LDT Users' Guide for the LISF Public 7.3.5 release.
=> Update revision history for the LDT Users' Guide for the LISF Public 7.3.5 release

docs/LDT_users_guide/LDT_usersguide.adoc, docs/LDT_users_guide/revision_table.adoc
Update revision history for the LDT Users' Guide for the LISF Public 7.3.5.
=> Update revision history for the LDT Users' Guide for the LISF Public 7.3.5

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/intro.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc, docs/LVT_users_guide/LVT_users_guide.adoc, docs/LVT_users_guide/intro.adoc, docs/LVT_users_guide/revision_table.adoc
Update revision history for Users' Guides for LISF Public 7.4.0 release
=> Update revision history for Users' Guides for LISF Public 7.4.0 release

lis/dataassim/obs/WUS_UCLAsnow/WUS_UCLAsnowMod.F90
=> Update inline documentation

lis/metforcing/genMetForc/timeinterp_metForcGenerated.F90
=> Fix misspellings and cleanup in file

lis/metforcing/usaf/USAF_ImergHHMod.F90
Modified AGRMET IMERG reader to support IMERG V07.  
Based on sample files provided by Erich Stocher/Code 610.2.  Reader continues to provide backward support for IMERG V06.
=> Modified LIS AGRMET to support IMERG V6 and IMERG V7.

ldt/core/LDT_climateParmsMod.F90
Fixed several integer format codes to ensure positive number of digits.
This bug was detected by the GNU compilers.  (Original code worked w/o issue with Intel compilers.)
=> Fixed integer format statements.

ldt/testcases/DAobs_ESA-CCI_passive/README, ldt/testcases/DAobs_ESA-CCI_passive/ldt.config, lis/testcases/dataassim/ESA-CCI_passive_sm/MODEL_OUTPUT_LIST.TBL, lis/testcases/dataassim/ESA-CCI_passive_sm/README, lis/testcases/dataassim/ESA-CCI_passive_sm/lis.config, lis/testcases/dataassim/ESA-CCI_passive_sm/output.ctl, lis/testcases/dataassim/ESA-CCI_passive_sm/testcase.ctl
Add the passive ESA-CCI soil moisture testcase.
=> Add the passive ESA-CCI soil moisture testcase

lis/dataassim/obs/CDFS_GVF/CDFSgvf_Mod.F90, lis/dataassim/obs/CDFS_GVF/read_CDFSgvf.F90, lis/dataassim/obs/CDFS_GVF/write_CDFSgvfobs.F90, lis/dataassim/obs/SMAP_E_OPLsm/SMAPEOPLsm_Mod.F90, lis/dataassim/obs/SMAP_E_OPLsm/read_SMAPEOPLsm.F90, lis/dataassim/obs/SMAP_E_OPLsm/write_SMAPEOPLsmobs.F90, lis/dataassim/obs/VIIRS_GVF/VIIRSgvf_Mod.F90, lis/dataassim/obs/VIIRS_GVF/read_VIIRSgvf.F90, lis/dataassim/obs/VIIRS_GVF/write_VIIRSgvfobs.F90, lis/make/default.cfg, lis/plugins/LIS_DAobs_pluginMod.F90, lis/plugins/LIS_lsmda_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90
Codes for VIIRS GVF, CDFS GVF, and SMAP_E_OPL soil moisture DA have been added in LIS
SMAP_E_OPL DA: /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noah39/noah39_CONUS_10km/DA_MCDF_SMAP_E_OPL
VIIRS GVF DA:
/discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_VIIRS_GVF
CDFS GVF DA:
/discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_CDFS_GVF
=> New features in LIS for GVF DA and SMAP_E_OPL soil moisture DA

lvt/datastreams/LISDAobs/LISda_obsMod.F90
LVT DAobs reader was updated to support Lambert projection. 
Resolves #1151
Test case for lambert projection 
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/Analysis/us_map
lvt.config.ol.da.DAobs
job.ol.da
Testcase to make sure it did not break the latlon projection. 
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/nlads_conus/Analysis/us_map
*Before code update
lvt.config.ol.da.DAobs
job.ol.da
Output @ 
STATS.ol.da.DAobs
* After code update 
lvt.config.ol.da.DAobs.test
job.ol.da.test
Output @ 
STATS.ol.da.DAobs.test
=> Support for Lambert projection added to LVT LISDAobs reader.

lvt/testcases/datastreams/IMERG/METRICS.TBL, lvt/testcases/datastreams/IMERG/README, lvt/testcases/datastreams/IMERG/input.ctl, lvt/testcases/datastreams/IMERG/lvt.config, lvt/testcases/datastreams/IMERG/output.ctl, lvt/testcases/datastreams/IMERG/testcase.ctl
Add the LVT IMERG reader testcase
=> Add the LVT IMERG reader testcase

lis/surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90
See commit 661232d0a1d33aa09f7e002d2c7ad99a3a196ff3 for more details.
=> Set length of dimID to 11

ldt/SMAP_E_OPL/ARFSSMRETRIEVAL.F90, ldt/SMAP_E_OPL/LDT_smap_e_oplMod.F90, lis/make/Makefile, lis/make/user_557ww.cfg
This resolves compiler errors raised by both the GNU and Cray compilers.
=> Fixes for compiling with GNU and Cray compilers

lis/utils/usaf/retune_bratseth/scripts/autotune.py, lis/utils/usaf/retune_bratseth/scripts/create_blacklist.py, lis/utils/usaf/retune_bratseth/scripts/customize_lis_config.py, lis/utils/usaf/retune_bratseth/scripts/customize_procoba_nwp.py, lis/utils/usaf/retune_bratseth/scripts/customize_procoba_sat.py, lis/utils/usaf/retune_bratseth/scripts/fit_semivariogram.py, lis/utils/usaf/retune_bratseth/scripts/plot_semivariogram.py, lis/utils/usaf/retune_bratseth/scripts/rescale_sat_sigma2.py, lis/utils/usaf/retune_bratseth/scripts/semivar.py
This updates the bratseth_retune scripts to boost the scores from pylint 2.15.5.
There are still a few findings that require significant reorganization/refactoring of code into smaller components.  That work is deferred to a later date.
=> Updates to retune_bratseth scripts to boost pylint scores

docs/LIS_users_guide/build.adoc, docs/LIS_users_guide/user_cfg_table.adoc, lis/configs/lis.config.adoc
This reformats, fixes, and updates the LIS Users' Guide for the upcoming LISF 557WW 7.5 release.
=> Corrections to LIS Users' Guide

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LISF_installation_guide/LISF_installation_guide.adoc, docs/LISF_installation_guide/revision_table.adoc, docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc, docs/LVT_users_guide/LVT_users_guide.adoc, docs/LVT_users_guide/revision_table.adoc
Update revision history for Users' Guides for LISF 557WW 7.5.0 release
=> Update revision history for Users' Guides for LISF 557WW 7.5.0 release

ldt/configs/ldt.config.adoc, ldt/core/LDT_LMLCMod.F90, ldt/core/LDT_paramProcMod.F90, ldt/core/LDT_paramTileInputMod.F90, ldt/params/landcover/read_MCD12Q1_lc.F90, ldt/params/mask/read_maskfile.F90, ldt/params/mask/read_maskfile_MCD12Q1.F90, ldt/plugins/LDT_param_pluginMod.F90, ldt/plugins/LDT_pluginIndices.F90
Added support for reading MODIS IGBP landcover (MCD12Q1) within LDT that can now use annual landcover datasets
/discover/nobackup/projects/eis_freshwater/sahmad3/LIS_AMAZON/LDT_LCchange_TESTCASE
=> Adds support for MCD12Q1 landcover

lis/LICENSES/CNRS_CECILL_C_v1_Crocus8.1.txt
Add CECILL_C license for Crocus8.1
=> Add CECILL_C license for Crocus8.1

lis/plugins/LIS_lsmrouting_pluginMod.F90, lis/surfacemodels/land/jules.5.0/routing/jules50_getrunoffs_hymap2.F90, lis/surfacemodels/land/jules.5.0/routing/jules50_getsws_hymap2.F90
Add codes to run JULES 5.0 with HyMAP2 router
Resolves https://github.com/NASA-LIS/LISF/issues/1285
This is a rework of PR #1286 from yyoon4. 
/discover/nobackup/yyoon4/lis7/Testcase/hymap_jules50
=> Support JULES5.0 + HyMAP2 run

.github/workflows/build-release-docs.yaml
Cherry-pick this fix from the master branch.
=> Fix release docs action

lis/configs/lis.config.adoc, lis/make/default.cfg, lis/metforcing/geos_it/0Intro_geosit.txt, lis/metforcing/geos_it/finalize_geosit.F90, lis/metforcing/geos_it/geosit_forcingMod.F90, lis/metforcing/geos_it/get_geosit.F90, lis/metforcing/geos_it/read_geosit.F90, lis/metforcing/geos_it/read_geosit_elev.F90, lis/metforcing/geos_it/readcrd_geosit.F90, lis/metforcing/geos_it/reset_geosit.F90, lis/metforcing/geos_it/timeinterp_geosit.F90, lis/plugins/LIS_metforcing_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90
This pull request adds the GEOS-IT hourly surface products as a metforcing into LIS.  There are options available to use forcings at different heights above the ground.
Resolves #1320
=> Add GEOS-IT as a metforcing for LIS

lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.hymap, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.hymap, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.hymap, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid
Fixed output intervals and RAPID time step.
=> [GHI] Further fixes to NRT-Streamflow FOC files.

lvt/utils/usaf/make_sm_geotiff.py
GeoTIFF files produced by make_sm_geotiff.py now follow 557 WW filename convention.
=> Updated script to output GeoTIFF files with 557 WW filename convention.

lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.hymap.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.hymap.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.hymap.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem.0p25deg
Restored older lis.config files for deterministic GALWEM MR runs.
Note:  Filenames were changed slightly to emphasize these are for MR.
=> Restored deterministic GALWEM MR lis.config files.

lvt/utils/usaf/make_sm_geotiff.py
Updated soil moisture GeoTIFF filenames after consultation with 557WW and LCMC.
=> [GHI] Updated SM GeoTIFF filenames after consultation with 557WW and LCMC.

lis/configs/557WW-7.5-FOC/MRF_GHI/ldt.config.mr.jules50.gd, lis/configs/557WW-7.5-FOC/MRF_GHI/ldt.config.mr.jules50.hymap.gd, lis/configs/557WW-7.5-FOC/MRF_GHI/ldt.config.mr.noah39.gd, lis/configs/557WW-7.5-FOC/MRF_GHI/ldt.config.mr.noah39.hymap.gd, lis/configs/557WW-7.5-FOC/MRF_GHI/ldt.config.mr.noahmp401.gd, lis/configs/557WW-7.5-FOC/MRF_GHI/ldt.config.mr.noahmp401.hymap.gd, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.hymap.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.hymap.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.hymap.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.hymap, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.hymap, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.hymap, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid
Updated FOC files for NRT-Streamflow, Bridge, and MR.
=> Updated FOC files

docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc
Update revision history for Users' Guides for LISF 557WW 7.5.5 release.
=> Update revision history for Users' Guides for LISF 557WW 7.5.5 release

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/temporal_disaggregation_6hourly_module.py, lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/temporal_disaggregation_nmme_6hourly_module.py
This is related to [Issue 1364](https://github.com/NASA-LIS/LISF/issues/1364)
=> fixed a bug that had made 6-hourly precip values constants

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc, docs/LVT_users_guide/LVT_users_guide.adoc, docs/LVT_users_guide/revision_table.adoc
Tweaked user guides to reflect new 557WW release.
=> Bumped up user guide revision numbers for LISF 557WW 7.5.8 release.

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc, docs/LVT_users_guide/LVT_users_guide.adoc, docs/LVT_users_guide/revision_table.adoc
Bumped up user guide revisions for LISF 557WW 7.5.9 release.
=> Bumped up user guide revisions for LISF 557WW 7.5.9 release.

lis/metforcing/imerg/read_imerg.F90
Fix compiler error raised by the GNU gfortran compiler.
=> Fix GNU Fortran compiler error

lis/utils/usaf/s2s/README_GHI-S2S_LIS7.5, lis/utils/usaf/s2s/s2s_app/s2s_config_global_fcast, lis/utils/usaf/s2s/s2s_app/s2s_config_global_hcast, lis/utils/usaf/s2s/s2s_app/s2s_run.sh, lis/utils/usaf/s2s/s2s_app/verify_tiff.py, lis/utils/usaf/s2s/s2s_modules/s2splots/plot_anom_verify.py, lis/utils/usaf/s2s/s2s_modules/s2splots/plot_s2smetrics.py, lis/utils/usaf/s2s/s2s_modules/s2splots/plot_utils.py
Updates include:
- Corrections to some file comments and README file
- Minor updates to the main run script
- Corrected monthly total precip conversion in s2splots
- Modified some domains in s2splots and added two new ones
- Minor correction to a verification script
=> Final S2S LIS 7.5.11 Code Updates

lis/core/LIS_fileIOMod.F90, lis/core/LIS_historyMod.F90, lis/core/LIS_logMod.F90, lis/core/LIS_timeMgrMod.F90, lis/metforcing/galwem/read_galwem.F90, lis/metforcing/galwem_ge/read_galwemge.F90, lis/metforcing/usaf/AGRMET_cdfs2_est.F90, lis/metforcing/usaf/AGRMET_fillgaps.F90, lis/metforcing/usaf/AGRMET_fldbld.F90, lis/metforcing/usaf/AGRMET_fldbld_galwem.F90, lis/metforcing/usaf/AGRMET_fldbld_gfs.F90, lis/metforcing/usaf/AGRMET_fldbld_precip_galwem.F90, lis/metforcing/usaf/AGRMET_fldbld_precip_gfs.F90, lis/metforcing/usaf/AGRMET_forcingMod.F90, lis/metforcing/usaf/AGRMET_getpcpobs.F90, lis/metforcing/usaf/AGRMET_julhr_date10.F90, lis/metforcing/usaf/AGRMET_makest.F90, lis/metforcing/usaf/AGRMET_read_sfcalccntm.F90, lis/metforcing/usaf/AGRMET_readmask.F90, lis/metforcing/usaf/AGRMET_readpcpcntm.F90, lis/metforcing/usaf/AGRMET_readterrain.F90, lis/metforcing/usaf/USAF_ImergHHMod.F90, lis/metforcing/usaf/USAF_bratsethMod.F90, lis/metforcing/usaf/readagrmetforcinganalysis.F90, lis/metforcing/usaf/readcrd_agrmet.F90
Added alert files for missing or bad IMERG files.
Also extended alert messages to 255, and lengthened maximum length of alert filename.
=> Added alerts for missing/bad IMERG files.

docs/working_with_github/working_with_github.adoc
Add section "Explicitly add files".  This provides guidance on how to run the `git add` command.
=> Add section "Explicitly add files"

lis/utils/usaf/s2s/s2s_app/s2s_hcst_preprocess.sh, lis/utils/usaf/s2s/s2s_app/submit_hcast.sh, lis/utils/usaf/s2s/s2s_app/wget_cfsv2_oper_ts_e2es.sh, lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_forecast_climatology.py, lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_nmme_forecast_climatology.py, lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_observational_climatology.py, lis/utils/usaf/s2s/s2s_modules/s2splots/plot_mena.py
A few of the S2S scripts have been fixed or updated:
- BCSD climatology file generation scripts now include compression (or deflation) flags to reduce size of the clim files.
- Increased the slurm job request times for the BCSD climatology generation, as it takes a bit longer to write the nc files with deflation turned on.
- Added fix for confirming that CFSv2 forecast files are present in source directory before proceeding with E2ES run.
- Minor fix to the hindcast submit shell script (corrected month parameter name).
- Minor fix to the s2splots - MENA-script, to plot total monthly precip.
Providing these commits for any future bug - patch related needs.
=> Minor S2S Code Updates

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc
Update revision history for the LDT Users' Guides for the upcoming LISF Public 7.4.3 release.
=> Update revision history for Users' Guides for LISF Public 7.4.3 release

lis/utils/usaf/s2s/s2s_app/s2s_run.sh, lis/utils/usaf/s2s/s2s_app/wget_cfsv2_oper_ts_e2es.sh, lis/utils/usaf/s2s/s2s_modules/shared/utils.py
- Update to s2s run script with comment out for user prompt
- Update to main utils module to allow user to specify any slurm constraint
- Minor text updates and one typo fix for wget script
Final updates have been tested with May- and Sept-2023 use cases on Discover.  All good to go.
=> S2S Runtime Script Updates

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/process_forecast_data.py, lis/utils/usaf/s2s/s2s_modules/s2splots/plot_anom_verify.py
- Update to the CFSv2 processing python script to account for year-crosssover for January, which has pentad-date members in prior December+year.
- Minor unit update for one s2splots verification plotting script (no impact on any processing of files or LIS runs).
All code has been fully tested on different months and cases. All results check out correctly.
Intended for final LIS 7.5 patch (LISF7.5.14)
@emkemp @jvgeiger
=> Update to S2S forecast processing script

lis/testcases/misc/dist_binary_rst/NOAHMP_OUTPUT_LIST.TBL, lis/testcases/misc/dist_binary_rst/README, lis/testcases/misc/dist_binary_rst/lis.config, lis/testcases/misc/dist_binary_rst/module_sf_noahmplsm_401.F90, lis/testcases/misc/dist_binary_rst/output.ctl, lis/testcases/misc/dist_binary_rst/output_innov.ctl, lis/testcases/misc/dist_binary_rst/testcase.ctl, lis/testcases/misc/dist_binary_rst/testcase_innov.ctl
Add testcase files for distributed binary restart testcase.
=> Add testcase files for distributed binary restart testcase

ldt/DAobs/GRACE_tws/readGRACEtwsObs.F90, lis/configs/lis.config.adoc, lis/dataassim/obs/ESACCI_sm/read_ESACCIsm.F90, lis/dataassim/obs/MCD15A3H_LAI/MCD15A3Hlai_Mod.F90, lis/dataassim/obs/MCD15A3H_LAI/read_MCD15A3Hlai.F90, lis/dataassim/obs/MCD15A3H_LAI/write_MCD15A3Hlai.F90, lis/interp/map_utils.F90, lis/make/default.cfg, lis/plugins/LIS_DAobs_pluginMod.F90, lis/plugins/LIS_lsmda_pluginMod.F90, lis/plugins/LIS_pluginIndices.F90, lis/runmodes/smootherDA/smootherDA_runMod.F90, lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90, lis/surfacemodels/land/noahmp.4.0.1/da_soilm/noahmp401_soilm_DAlog.F90, lis/surfacemodels/land/noahmp.4.0.1/noahmp_driver_401.F90, lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90, lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
A few changes made to LDT and LIS to support the Global-DA version 2 for the EIS project.
=> Add support for Global DA v2

lis/utils/usaf/s2s/s2s_app/s2s_hcst_preprocess.sh, lis/utils/usaf/s2s/s2s_app/wget_cfsv2_oper_ts_e2es.sh
- Corrected the year directory placement for January forecast files, where members are made up of December dates of prior year.
- Also, increased slurm request hours for BCSD hindcast preprocessing. (since time outs have been occurring recently on Discover)
=> S2S CFSv2 script update

env/narwhal/lisf_7.5_prgenv_intel_8.3.3
I was able to install GDAL (and thus FortranGIS) on narwhal.
This commit completes this modulefile.
=> Add GDAL and FortranGIS to modulefile for narwhal

lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem-ge, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem-ge, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem-ge, lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem.0p25deg, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid
Fixed RAPID routing model time step in FOC files.  
THESE CHANGES NEED TO BE PROPOGATED TO MASTER.
Thanks to Yeosang Yoon for finding the error.
=> Fixed RAPID routing model time step.

ldt/utils/usaf/SMAP_E_OPL/customize_ldt_smapeopl_config.py, ldt/utils/usaf/SMAP_E_OPL/ldt.config.smapeopl.jules.tmpl, ldt/utils/usaf/SMAP_E_OPL/ldt.config.smapeopl.noah.tmpl, ldt/utils/usaf/SMAP_E_OPL/ldt.config.smapeopl.noahmp.tmpl, ldt/utils/usaf/SMAP_E_OPL/run_smap_e_opl_discover.sh
Added scripts to automate SMAP_E_OPL retrievals on Discover.
This is intended for upcoming 557 WW LISF 7.6 release.
=> Add scripts for automating SMAP_E_OPL retrievals

lis/metforcing/usaf/USAF_GagesMod.F90, lis/metforcing/usaf/USAF_PreobsReaderMod.F90
Bug fixes to ensure files are closed and file unit numbers are released.
=> Bug fixes to ensure files are closed and file unit numbers released.

lis/configs/lis.config.adoc, lis/metforcing/usaf/AGRMET_forcingMod.F90, lis/metforcing/usaf/AGRMET_sfcalc.F90, lis/metforcing/usaf/USAF_bratsethMod.F90, lis/metforcing/usaf/USAF_fldbld_radflux.F90, lis/metforcing/usaf/USAF_fldbld_radflux_galwem.F90, lis/metforcing/usaf/USAF_fldbld_radflux_gfs.F90, lis/metforcing/usaf/get_agrmet.F90, lis/metforcing/usaf/readagrmetforcing.F90, lis/metforcing/usaf/readcrd_agrmet.F90, lis/surfacemodels/land/noah.3.9/noah39_readrst.F90
ROUGH DRAFT, DO NOT MERGE
New capability to use GALWEM or GFS radiation in AGRMET Ops mode.
=> New capability to use GALWEM or GFS radiation in AGRMET Ops mode.

lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.noah39.galwem17, lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.noahmp401.galwem17, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid, lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid, lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
Updates IMERG version and radiation settings, for latest patches to support/lisf-557ww-7.5.
=> Updated FOC settings for latest patches

docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc, lis/configs/lis.config.adoc
Update LIS Users Guide for LISF 557WW 7.5.15 release.
=> Update LIS Users Guide for LISF 557WW 7.5.15 release

lis/utils/usaf/s2s/s2s_modules/shared/utils.py
Few updated lines of python code required for our LIS 7.5 patch
Added two new lines
_f.write('#SBATCH --exclusive' + '\n')   NEW LINE
_f.write('#SBATCH --mem=0' + '\n') 
Changed the numpy entry of “np.int” to just “int” -- Python 3.10 has depreciated np.int
=> a quick patch for 16WW

lis/utils/usaf/s2s/for_discover/lis/lis.config.s2sglobal.noahmp401_12mem.hymap2.DARun, lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template, lis/utils/usaf/s2s/s2s_modules/lis_darun/template_files/lis.config_template.GLOBAL
Add these entries to the S2S related lis.config files:
```
AGRMET radiation derived from:
AGRMET GALWEM radiation data directory:
```
=> Add new AGRMET related runtime configuration settings

lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
Add missing AGRMET related runtime configuration
=> Add missing AGRMET related runtime configuration

lis/testcases/dataassim/SMOPSv4/MODEL_OUTPUT_LIST.TBL, lis/testcases/dataassim/SMOPSv4/README, lis/testcases/dataassim/SMOPSv4/lis.config, lis/testcases/dataassim/SMOPSv4/output.ctl, lis/testcases/dataassim/SMOPSv4/testcase.ctl
Add SMOPSv4 testcase.  See PR #1544.
=> Add SMOPSv4 testcase

lis/utils/usaf/s2s/s2s_modules/s2splots/plot_utils.py
The error message came with Python 3.10 in s2s_modules/s2splots/plot_utils.py was resolved.
=> Support/lisf 557ww 7.5 patch3

lis/testcases/dataassim/SMOPSv4/lis.config, lis/testcases/dataassim/smos_nrt_nn_l2sm/lis.config
Add
```
AGRMET radiation derived from:
AGRMET cloud data directory:
AGRMET GALWEM radiation data directory:
```
to the lis.config files in the test suite.
=> Add new AGRMET settings to testcase lis.config files

docs/LISF_installation_guide/LISF_installation_guide.adoc, docs/LISF_installation_guide/revision_table.adoc
Update LISF Installation Guide for LISF 7.5.1 public release.
=> Update LISF Installation Guide for LISF 7.5.1 public release

docs/LIS_users_guide/obtain-source.adoc, lis/configs/lis.config.adoc
This adds the GLASS LAI and GLASS Albedo configs to the documentation and the LIS Users' Guide.
Resolves: #839
=> Add GLASS LAI and GLASS Albedo configs to the LIS Users' Guide.

lis/testcases/dataassim/SMOPSv4/lis.config, lis/testcases/dataassim/smos_nrt_nn_l2sm/lis.config
Add new, required AGRMET settings to testcase lis.config files
=> Add new, required AGRMET settings to testcase lis.config files

lis/testcases/dataassim/nasa_smap_enkf_noah36/lis.config, lis/testcases/irrigation/noahmp3.6_gw/lis.config.GWoff, lis/testcases/irrigation/noahmp3.6_gw/lis.config.GWon, lis/testcases/metforcing/mrms/lis.config.mask, lis/testcases/metforcing/mrms/lis.config.nomask, lis/testcases/metforcing/nldas2/lis.config, lis/testcases/surfacemodels/land/noah.3.6_cmem3/lis.config, lis/testcases/surfacemodels/land/noahmp.3.6_cmem3/lis.config, lis/testcases/surfacemodels/land/ruc.3.7/lis.config, lis/testcases/surfacemodels/land/vic.4.1.1/lis.config
Update testcases using `Met forcing source: NLDAS2`
See PR #1578.
=> Update testcases using NLDAS2 Met forcing source

lis/testcases/metforcing/nldas2_netcdf/NOAHMP401_OUTPUT_LIST.TBL.forcing, lis/testcases/metforcing/nldas2_netcdf/NOAHMP401_OUTPUT_LIST.TBL.forcing.FORB, lis/testcases/metforcing/nldas2_netcdf/README, lis/testcases/metforcing/nldas2_netcdf/input.ctl, lis/testcases/metforcing/nldas2_netcdf/input_testcase.ctl, lis/testcases/metforcing/nldas2_netcdf/ldt.config, lis/testcases/metforcing/nldas2_netcdf/lis.config.nldas.grib, lis/testcases/metforcing/nldas2_netcdf/lis.config.nldas.grib.FORB, lis/testcases/metforcing/nldas2_netcdf/lis.config.nldas.netcdf, lis/testcases/metforcing/nldas2_netcdf/lis.config.nldas.netcdf.FORB, lis/testcases/metforcing/nldas2_netcdf/output_grib.ctl, lis/testcases/metforcing/nldas2_netcdf/output_grib_b.ctl, lis/testcases/metforcing/nldas2_netcdf/output_netcdf.ctl, lis/testcases/metforcing/nldas2_netcdf/output_netcdf_b.ctl, lis/testcases/metforcing/nldas2_netcdf/testcase_grib.ctl, lis/testcases/metforcing/nldas2_netcdf/testcase_grib_b.ctl, lis/testcases/metforcing/nldas2_netcdf/testcase_netcdf.ctl, lis/testcases/metforcing/nldas2_netcdf/testcase_netcdf_b.ctl
Add testcase for NLDAS2 NetCDF metforcing reader
See PR #1578.
=> Add testcase for NLDAS2 NetCDF metforcing reader

ldt/USAFSI/LDT_usafsiMod.F90, ldt/USAFSI/USAFSI_analysisMod.F90, ldt/USAFSI/USAFSI_arraysMod.F90, ldt/USAFSI/USAFSI_espcdMod.F90, ldt/USAFSI/USAFSI_run.F90, ldt/USAFSI/ldt.config.sample, ldt/configs/ldt.config.adoc
Add option to use ESPC-D output instead of GOFS for SST and sea ice.
=> Add ESPC-D support

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc
Update revision history for LDT Users' Guide for LISF 557WW 7.5.18 release.
=> Update revision history for LDT Users' Guide for LISF 557WW 7.5.18 release

lis/metforcing/usaf/AGRMET_storeobs.F90, lis/metforcing/usaf/AGRMET_storeobs_offhour.F90
Fix to argument size mismatches.
This was detected by Jim Geiger using the Cray compiler.
=> Fix to argument size mismatches.

lis/core/LIS_PRIV_rcMod.F90, lis/core/LIS_process_cmd_args.F90
Increase the length of lis_config_file to LIS_CONST_PATH_LEN.
=> Increase length of lis_config_file to LIS_CONST_PATH_LEN

lis/testcases/metforcing/gefsoperforcing/lis.config
I slightly restructured in input tarball.  This corrects the path to the GEFS input data.
=> Correct GEFS operational testcase

ldt/USAFSI/USAFSI_amsr2Mod.F90, ldt/USAFSI/USAFSI_analysisMod.F90, ldt/USAFSI/USAFSI_espcdMod.F90, ldt/USAFSI/USAFSI_run.F90, ldt/USAFSI/USAFSI_ssmisMod.F90, ldt/USAFSI/USAFSI_utilMod.F90, ldt/USAFSI/USAFSI_xcalgmiMod.F90
Porting PR #1622 into support/lisf-557ww-7.5.
=>  Revised alert and abort message files for USAFSI

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/process_forecast_data.py, lis/utils/usaf/s2s/s2s_modules/shared/utils.py
Minor updates to two S2S scripts, addressing
some minor pylint fixes.
=> Final S2S Python updates 

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc, ldt/configs/ldt.config.adoc
Update revision history for LDT Users' Guide for LISF 557WW 7.5.19 release
=> Update revision history for LDT Users' Guide for LISF 557WW 7.5.19 release

lis/testcases/misc/dynamic_lapse_rate/MODEL_OUTPUT_LIST.TBL, lis/testcases/misc/dynamic_lapse_rate/README, lis/testcases/misc/dynamic_lapse_rate/input.ctl, lis/testcases/misc/dynamic_lapse_rate/input_testcase.ctl, lis/testcases/misc/dynamic_lapse_rate/ldt.config, lis/testcases/misc/dynamic_lapse_rate/lis.config, lis/testcases/misc/dynamic_lapse_rate/output.ctl, lis/testcases/misc/dynamic_lapse_rate/testcase.ctl
Add testcase files for dynamic lapse rate testcase.
See PR #1630.
=> Add testcase files for dynamic lapse rate testcase

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LISF_installation_guide/LISF_installation_guide.adoc, docs/LISF_installation_guide/additional_platforms.adoc, docs/LISF_installation_guide/platforms.adoc, docs/LISF_installation_guide/revision_table.adoc, docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc, docs/LVT_users_guide/LVT_users_guide.adoc, docs/LVT_users_guide/revision_table.adoc
Update revision history for LISF Users Guides for LISF 557WW 7.6.0 release.
=> Update revision history for LISF Users Guides for LISF 557WW 7.6.0 release

lis/core/LIS_historyMod.F90
Cherry-pick the commit from pull request #1628 to the support/lisf-public-7.5 branch.
=> Fix the bug in writing model output in 2D ensemble grid space #1627

lis/configs/557WW-7.6-FOC/MR/ldt_bridge/ldt.config.bridge.noah39.76, lis/configs/557WW-7.6-FOC/MR/ldt_bridge/ldt.config.bridge.noahmp401.76
Updated MR Bridge FOC files to reduce static data processing to absolute minimum required.  This changes the wallclock times from 14-15 minutes to 2-3 minutes.
Many thanks to @karsenau for guidance on changing the LDT settings.
=> Updated MR Bridge FOC files

.github/workflows/build-release-docs.yaml
Specify the version of css_parser package.
=> Fix the Create Release Docs action

lis/testcases/dataassim/smos_nrt_nn_l2sm/lis.config
Add new AGRMET settings to SMOS NRT testcase lis.config file.
=> Add new AGRMET settings to SMOS NRT testcase lis.config file

ldt/testcases/ESPC-D/README, ldt/testcases/ESPC-D/input.ctl, ldt/testcases/ESPC-D/ldt.config, ldt/testcases/ESPC-D/output.ctl, ldt/testcases/ESPC-D/testcase.ctl
=> Add ESPC-D testcase files

lis/utils/usaf/s2s/s2s_modules/lis_darun/template_files/lis.config_template.GLOBAL, lis/utils/usaf/s2s/s2s_modules/lis_fcst/template_files/template_lis.config.s2sglobal.noahmp401.hymap2.da_ics_forecast, lis/utils/usaf/s2s/s2s_modules/lis_fcst/template_files/template_lis.config.s2sglobal.noahmp401.hymap2.da_ics_hindcast
Made additions to the S2S LIS config template files for the latest
LIS 7.6 557 WW support branch.
For ticket #1681:
https://github.com/NASA-LIS/LISF/issues/1681
No test case required for this submission.  The updates have been thoroughly tested and documented.
=> Minor updates to 7.6 LIS config files for S2S

docs/LDT_users_guide/LDT_users_guide.adoc, docs/LDT_users_guide/revision_table.adoc, docs/LIS_users_guide/LIS_users_guide.adoc, docs/LIS_users_guide/revision_table.adoc
Update revision history for Users' Guides for LISF Public 7.5.3 release
=> Update revision history for Users' Guides for LISF Public 7.5.3 release
